# Imports

In [2]:
import numpy as np
import torch

# Creating Tensors

## From Python Data Structures

In [3]:
# From lists
vector = torch.tensor([1, 2, 3, 4])
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"Vector shape: {vector.shape}")
print(f"Matrix shape: {matrix.shape}")
print(f"3D tensor shape: {tensor_3d.shape}")

Vector shape: torch.Size([4])
Matrix shape: torch.Size([2, 3])
3D tensor shape: torch.Size([2, 2, 2])


## From Numpy Arrays

In [6]:
numpy_array = np.array([1,2,3])
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_copy = torch.tensor(numpy_array)


print(f"original numpy array: {numpy_array}")
print(f"tensor from numpy: {tensor_from_numpy}")
print(f"tensor_copy: {tensor_copy}")

original numpy array: [1 2 3]
tensor from numpy: tensor([1, 2, 3])
tensor_copy: tensor([1, 2, 3])


## Special Tensor Creation Functions

In [9]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
torch.eye(4,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [15]:
torch.rand(2,4)

tensor([[0.8164, 0.9770, 0.0129, 0.2732],
        [0.5355, 0.8141, 0.6632, 0.0899]])

In [18]:
# standard normal
torch.randn(2,4)

tensor([[-0.4059, -0.7304, -2.4784,  0.0544],
        [ 0.0829, -2.9344,  0.8752, -0.1511]])

In [20]:
# random intergers, low,high, size
torch.randint(0,4,(2,4))

tensor([[1, 2, 2, 0],
        [1, 3, 0, 1]])

In [22]:
# filled with specific values
torch.full((2,3), 7.5)

tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])

In [24]:
# linearly spaced
torch.linspace(1,5,8)

tensor([1.0000, 1.5714, 2.1429, 2.7143, 3.2857, 3.8571, 4.4286, 5.0000])

# Essential Tensor Properties

In [25]:
tensor = torch.randn(3,4,5)

In [28]:
print(f"tensor_shape: {tensor.shape}")
print(f"data type: {tensor.dtype}")
print(f"Device: {tensor.device}")
print(f":Requires Gradient {tensor.requires_grad}")
print(f"Number or elements: {tensor.numel()}")

tensor_shape: torch.Size([3, 4, 5])
data type: torch.float32
Device: cpu
:Requires Gradient False
Number or elements: 60


# Tensor Operations: Beyond NumPy

## Arithmetic Operations

In [29]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

In [30]:
add1 = a + b
add2 = torch.add(a,b)
add3 = a.add(b)

print(f"add1: {add1}")
print(f"add2: {add2}")
print(f"add3: {add3}")

add1: tensor([[ 6,  8],
        [10, 12]])
add2: tensor([[ 6,  8],
        [10, 12]])
add3: tensor([[ 6,  8],
        [10, 12]])


In [31]:
# scaled additions

scaled_add = torch.add(a,b, alpha=2) # a+2*b
scaled_add

tensor([[11, 14],
        [17, 20]])

## Matrix Operations

In [32]:
x = torch.randn(3, 4)
y = torch.randn(4, 5)

In [33]:
matmul1 = x.matmul(y)
matmul2 = x @ y
matmul3 = torch.mm(x,y) # only for 2-D tensors

element_wise = x * x

print(f"matmul1:{matmul1}")
print(f"matmul2:{matmul2}")
print(f"matmul3:{matmul3}")
print(f"element wise:{element_wise}")

matmul1:tensor([[-2.6480, -0.3734, -3.7430, -1.8007, -1.9437],
        [-1.9674, -0.6171, -0.6695,  2.1408, -2.4892],
        [-1.3993, -0.3063, -1.0599, -0.2092,  0.6514]])
matmul2:tensor([[-2.6480, -0.3734, -3.7430, -1.8007, -1.9437],
        [-1.9674, -0.6171, -0.6695,  2.1408, -2.4892],
        [-1.3993, -0.3063, -1.0599, -0.2092,  0.6514]])
matmul3:tensor([[-2.6480, -0.3734, -3.7430, -1.8007, -1.9437],
        [-1.9674, -0.6171, -0.6695,  2.1408, -2.4892],
        [-1.3993, -0.3063, -1.0599, -0.2092,  0.6514]])
element wise:tensor([[1.6167e+00, 3.6401e+00, 1.0368e-05, 9.8502e-03],
        [1.3825e+00, 7.5347e-02, 1.5675e+00, 3.4820e+00],
        [9.3346e-02, 1.1520e-03, 2.6908e+00, 2.6431e-01]])


## Reduction Operations

In [34]:
tensor = torch.randn(3, 4, 5)

# Global reductions
total_sum = torch.sum(tensor)
mean_value = torch.mean(tensor)
max_value = torch.max(tensor)

# Dimension-specific reductions
sum_dim0 = torch.sum(tensor, dim=0)  # Shape: [4, 5]
sum_dim1 = torch.sum(tensor, dim=1)  # Shape: [3, 5]

# Multiple dimensions
sum_dims = torch.sum(tensor, dim=[0, 2])  # Shape: [4]

print(f"Original: {tensor}")
print(f"Original shape: {tensor.shape}")
print(f"Sum along dim 0: {sum_dim0.shape}")
print(f"Sum along multiple dims: {sum_dims.shape}")

Original: tensor([[[-0.1618, -0.7268,  0.9754, -0.5236,  1.6792],
         [-0.8890,  1.1406, -0.9529, -0.6271,  1.3454],
         [ 0.6099,  0.5167, -0.1132,  0.6841, -1.2386],
         [-1.1246, -0.1782,  2.2038,  0.0100, -0.2533]],

        [[-0.0679,  0.5993, -1.0563, -0.0331,  0.7992],
         [-2.2053,  1.4867, -0.5018,  0.2173,  1.3603],
         [-1.1327, -0.4020, -1.0862, -0.8179, -1.9508],
         [-1.3342, -1.6493, -0.6656,  1.4484,  0.4194]],

        [[ 0.2422, -0.1554,  0.5541,  0.2547,  0.3117],
         [-1.0611,  3.0310, -1.9969, -0.8493,  2.8213],
         [-1.1637, -0.7653,  2.0314, -1.2741,  0.8449],
         [ 1.4980, -1.5383,  0.9549,  0.2376, -0.1333]]])
Original shape: torch.Size([3, 4, 5])
Sum along dim 0: torch.Size([4, 5])
Sum along multiple dims: torch.Size([4])


In [37]:
total_sum, max_value

(tensor(-0.3520), tensor(3.0310))

In [35]:
sum_dim0

tensor([[ 0.0125, -0.2829,  0.4732, -0.3020,  2.7901],
        [-4.1554,  5.6583, -3.4517, -1.2591,  5.5270],
        [-1.6865, -0.6506,  0.8320, -1.4079, -2.3445],
        [-0.9607, -3.3657,  2.4931,  1.6960,  0.0328]])

In [38]:
sum_dim1

tensor([[-1.5654,  0.7524,  2.1131, -0.4566,  1.5327],
        [-4.7402,  0.0347, -3.3100,  0.8147,  0.6281],
        [-0.4846,  0.5720,  1.5435, -1.6312,  3.8447]])

In [39]:
sum_dims

tensor([ 2.6909,  2.3191, -5.2574, -0.1046])

# GPU Acceleration

In [40]:
torch.cuda.is_available()

True

In [41]:
torch.cuda.device_count()

1

In [42]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [43]:
cpu_tensor = torch.randn(3, 3)
gpu_tensor = torch.randn(3, 3, device=device)

In [45]:
moved_tensor = cpu_tensor.to(device)

print(f"CPU tensor device: {cpu_tensor.device}")
print(f"GPU tensor device: {gpu_tensor.device}")
print(f"moved tensor device: {moved_tensor.device}")

CPU tensor device: cpu
GPU tensor device: cuda:0
moved tensor device: cuda:0


In [46]:
torch.cuda.memory_allocated()

1024

In [47]:
# Best practice: device-agnostic code
def create_model_tensors(device):
    weights = torch.randn(100, 50, device=device)
    bias = torch.zeros(50, device=device)
    return weights, bias

In [50]:
# Memory management for GPUs
if torch.cuda.is_available():
    torch.cuda.empty_cache()  # Clear GPU memory
    print(f"GPU memory allocated: {torch.cuda.memory_allocated()}")

GPU memory allocated: 1024


In [54]:
device

device(type='cuda')

In [57]:
large_tensor = torch.randn(1000, 1000, device = 'cuda')
result = torch.matmul(large_tensor, large_tensor.T)

print(f"Large tensor device: {large_tensor.device}")
print(f"Computation result shape: {result.shape}")

Large tensor device: cuda:0
Computation result shape: torch.Size([1000, 1000])


In [58]:
torch.cuda.memory_allocated()

20972544

# Data types

In [ ]:
# Data Type	        PyTorch dtype	                    Typical Use Case
# 32-bit float	    torch.float32 or torch.float	    Default for neural networks, models, gradients
# 64-bit float	    torch.float64 or torch.double	    High-precision scientific computing
# 16-bit float	    torch.float16 or torch.half	        Memory-efficient training
# 64-bit integer	torch.int64 or torch.long	        Default for indices, labels, counts
# 32-bit integer	torch.int32 or torch.int	        Smaller integer operations
# Boolean	        torch.bool	                        Masks, conditions


# The fundamental tension comes from PyTorch's defaults:

# Floating-point tensors default to float32 - perfect for neural network computations

# Integer tensors default to int64 - suitable for indexing and labels

# These don't mix automatically - leading to type mismatch errors

In [59]:
# This will cause a type error
predictions = torch.randn(10, 5)  # float32
labels = torch.randint(0, 5, (10,))  # int64

# CrossEntropyLoss expects float32 predictions and int64 labels - this works
loss = torch.nn.CrossEntropyLoss()(predictions, labels)

# But BCELoss expects both to be float32 - this fails
binary_labels = torch.randint(0, 2, (10,))  # int64
# loss = torch.nn.BCELoss()(predictions, binary_labels)  # ERROR!

In [60]:
float_tensor = torch.randn(3, 3)  # float32
int_tensor = torch.randint(0, 10, (3, 3))  # int64

# Basic arithmetic works due to type promotion
result = float_tensor + int_tensor  # Works - promotes to float32

# But matrix multiplication is stricter
# result = torch.matmul(float_tensor, int_tensor)  # ERROR!

In [ ]:
# PyTorch's Type Promotion Rules
# PyTorch does have limited automatic type promotion, but it's much more restrictive than NumPy:

# Promotion Hierarchy: complex ← float ← int ← bool

# Higher priority types dominate (float beats int, complex beats float)

# Same category, different sizes promote to larger size

# Different categories follow the hierarchy

In [61]:
# Automatic promotion examples
bool_tensor = torch.tensor([True, False])     # bool
int_tensor = torch.tensor([1, 2])             # int64
float_tensor = torch.tensor([1.0, 2.0])       # float32

# These work due to promotion
bool_plus_int = bool_tensor + int_tensor       # → int64
int_plus_float = int_tensor + float_tensor     # → float32

In [62]:
bool_plus_int

tensor([2, 2])

In [63]:
int_plus_float

tensor([2., 4.])

In [64]:
# Multiple ways to cast types
int_tensor = torch.randint(0, 10, (3, 3))

# Method 1: Using .to()
float_version = int_tensor.to(torch.float32)

# Method 2: Using dtype-specific methods
float_version = int_tensor.float()

# Method 3: During tensor creation
# float_tensor = torch.tensor(data, dtype=torch.float32)

In [65]:
# Memory and Performance Considerations
# Type choice affects performance and memory usage:

# float32 - Good balance for most deep learning (4 bytes per element)

# float16 - Half precision, saves memory but may lose precision (2 bytes per element)

# float64 - Double precision, uses more memory (8 bytes per element)

# int64 - Default for indices, may be overkill for small datasets (8 bytes per element)